/**
 * Generates the per-locale entry points under src/locales/ (gitignored).
 *
 * Each generated file embeds one language's dataset as literals and binds it
 * to the shared query factory, so a bundle built from `uzbgeo/<locale>`
 * carries exactly one language — roughly a quarter of the main entry's data.
 *
 * Runs as part of `bun run build` and `bun run test`. Regenerate manually
 * with `bun run generate:locales`.
 */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { regions } from "../src/data/regions";
import { districts } from "../src/data/districts";
import { cities } from "../src/data/cities";
import { getAllLines, getStationsByLine, getTransfers } from "../src/metro";
import type { LineId } from "../src/metro/types";
import type { LanguageCode } from "../src/types";
import {
  localizeRegion,
  localizeDistrict,
  localizeCity,
  localizeLine,
  localizeStation,
} from "../src/locale/project";

const LOCALES: readonly LanguageCode[] = ["en", "uz", "uzc", "ru"];
const LINE_IDS: readonly LineId[] = [
  "chilanzar",
  "uzbekistan",
  "yunusabad",
  "ring",
];

const OUT_DIR = join(import.meta.dir, "..", "src", "locales");

const HEADER = `// GENERATED by scripts/generate-locales.ts — do not edit.
// Regenerate with \`bun run generate:locales\`.
`;

const json = (value: unknown): string => JSON.stringify(value, null, 2);

function geoEntry(locale: LanguageCode): string {
  const localizedRegions = regions.map((r) => localizeRegion(r, locale));
  const localizedDistricts = districts.map((d) => localizeDistrict(d, locale));
  const localizedCities = cities.map((c) => localizeCity(c, locale));

  return `${HEADER}
import { createLocaleApi } from "../locale/api";
import type {
  LocalizedRegion,
  LocalizedDistrict,
  LocalizedCity,
} from "../locale/types";

export type {
  LocalizedRegion,
  LocalizedDistrict,
  LocalizedCity,
  LocalizedSubdivision,
  LocalizedLocatives,
} from "../locale/types";
export type {
  LanguageCode,
  RegionCategory,
  SubdivisionType,
  CitySubordination,
} from "../types";

/** The language this entry point is projected to. */
export const locale = ${json(locale)};

const regions: readonly LocalizedRegion[] = ${json(localizedRegions)};

const districts: readonly LocalizedDistrict[] = ${json(localizedDistricts)};

const cities: readonly LocalizedCity[] = ${json(localizedCities)};

const api = createLocaleApi({ regions, districts, cities });

export const getAllRegions = api.getAllRegions;
export const getRegion = api.getRegion;
export const getAllDistricts = api.getAllDistricts;
export const getDistrict = api.getDistrict;
export const getDistrictsByRegionId = api.getDistrictsByRegionId;
export const getAllCities = api.getAllCities;
export const getRegionalCities = api.getRegionalCities;
export const getCity = api.getCity;
export const getCitiesByRegionId = api.getCitiesByRegionId;
export const getCitiesByDistrictId = api.getCitiesByDistrictId;
`;
}

function metroEntry(locale: LanguageCode): string {
  const localizedLines = getAllLines().map((l) => localizeLine(l, locale));
  const stationsByLine = Object.fromEntries(
    LINE_IDS.map((id) => [
      id,
      getStationsByLine(id).map((s) => localizeStation(s, locale)),
    ]),
  );

  return `${HEADER}
import { createMetroApi } from "../../locale/metro-api";
import type { LineId } from "../../metro/types";
import type {
  LocalizedLine,
  LocalizedStation,
} from "../../locale/types";

export type { LocalizedLine, LocalizedStation } from "../../locale/types";
export type { LineId } from "../../metro/types";
export type { LanguageCode } from "../../types";

/** The language this entry point is projected to. */
export const locale = ${json(locale)};

const lines: readonly LocalizedLine[] = ${json(localizedLines)};

const stationsByLine: Readonly<Record<LineId, readonly LocalizedStation[]>> = ${json(stationsByLine)};

const transfers: readonly (readonly [string, string])[] = ${json(getTransfers())};

const api = createMetroApi({ lines, stationsByLine, transfers });

export const getAllStations = api.getAllStations;
export const getStation = api.getStation;
export const getStationsByLine = api.getStationsByLine;
export const getAllLines = api.getAllLines;
export const getLine = api.getLine;
export const getTransfers = api.getTransfers;
export const neighborsOnLine = api.neighborsOnLine;
`;
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(join(OUT_DIR, "metro"), { recursive: true });

for (const locale of LOCALES) {
  writeFileSync(join(OUT_DIR, `${locale}.ts`), geoEntry(locale));
  writeFileSync(join(OUT_DIR, "metro", `${locale}.ts`), metroEntry(locale));
}

console.log(
  `Generated ${LOCALES.length * 2} locale entries in src/locales/ (${LOCALES.join(", ")})`,
);
